### ISSUE TITLE
Multiple interpretations

### ISSUE THREAD

**Issue by danoneata** [danoneata/chalk#14]
Haskell's `diagrams` allows for multiple interpretations of the domain specific language (DSL). For example, the code
```haskell
mconcat . iterateN 3 (rotateBy (1/9)) $ triangle 1
```
can yield various outputs depending on how it is interpreted: the image on left, if interpreted as a diagram, or the third image, if interpreted as a trail.
![image](https://user-images.githubusercontent.com/819256/167637723-6f6bc4eb-cca4-4cd6-8316-60f4dcefa737.png)
(See [their manual](https://diagrams.github.io/doc/manual.html#the-traillike-class) for more information.)

This feature might be nice to have (it will allow drawing something like the [Hilbert curve](https://diagrams.github.io/gallery/Hilbert.html)), but I expect to be rather involved.

**Comment by srush** [comment]
I honestly could not figure this part of the docs out... It seemed cool, but maybe a bit too cool?

**Comment by danoneata** [comment]
Yes, I think you are right, it might be too confusing. If I really want that behavior, I guess I could have another data type that behaves differently. Specifically for paths (what is called `Trail`s in `diagrams`), I could potentially introduce a data type whose composition glues the end of a path to the start of the other (instead of overlapping them at their origins).

**Comment by srush** [comment]
Chalk now roughly has this. It's a bit more explicit in python since we don't have the ability of the type system to disambiguate. But that feels pretty close to what we are going to get. 

If we wanted we could make the "monoid" structure a bit more explicit. (maybe having a general associative mconcat operator). But we can't do magic haskell stuff like have `empty()` work for all the types.
