### ISSUE TITLE
Place the connecting arrow between the centers of two diagrams on their corresponding bounding boxes

### ISSUE THREAD

**Issue by danoneata** [danoneata/chalk#38]
I don't know if this would improve the visuals of the arrows, but I was wondering whether it would help to emulate the behaviour of [`connectOutside`](https://hackage.haskell.org/package/diagrams-lib-1.4.5.1/docs/Diagrams-TwoD-Arrow.html#v:connectOutside) from `diagrams` (but using bounding boxes instead of traces):

> The arrow lies on the line between the centres of the diagrams, but is drawn so that it stops at the boundaries of the diagrams

Ideally, I would like to be able to draw something [like this](https://diagrams.github.io/doc/quickstart.html#a-worked-example)

<img src="https://user-images.githubusercontent.com/819256/169715241-ab20b659-d393-4a82-8c60-45d2022b1ab8.png" height=200></img>

but without manually specifying the "cardinal" points of each arrow.

@srush What do you think? Is it worth investing time in something like this?

**Comment by srush** [comment]
It is a nice idea, and probably would not be so hard to do. However as you note, ours will not be as pretty since it will be to the square Box and not the "envelope" like in diagrams. 

I agree the Cardinal direction thing is a bit hacky and should be removed eventually if we figure out a better way. (Either way it should probably be tlrb not nwse to match the library). 

We might want to have a file of comp geometry functions if more things like this accumulate.

**Comment by srush** [comment]
Great. I'm not changing anything right now. I have a couple remaining wishlist items, I'll add them to issues. But generally finding it really useful.

**Comment by srush** [comment]
Think we can call this done-ish. Who knew arrows are so complicated.
